services:
  - type: web
    name: fb-video-downloader-bot
    runtime: docker
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ZYLA_API_KEY
        sync: false
      - key: PORT
        value: 10000
